<?php
require_once __DIR__ . '/../../includes/auth.php'; require_once __DIR__ . '/../../controllers/PaymentController.php';
requireLogin(); requireRole('admin'); $user = currentUser(); $message = ''; $error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') { requireValidCsrfToken(); $result = PaymentController::adminTransition((int) ($_POST['id'] ?? 0), $_POST['action'] ?? '', $_POST['reason'] ?? '', $user['id']); if ($result['success']) $message = $result['message']; else $error = $result['message']; }
$date = trim((string) ($_GET['fecha'] ?? '')); if ($date !== '' && !preg_match('/^\d{4}-\d{2}-\d{2}$/', $date)) $date = '';
$filters = ['estado' => $_GET['estado'] ?? '', 'evento_id' => (int) ($_GET['evento_id'] ?? 0), 'fecha' => $date]; $payments = PaymentController::adminPayments($filters);
$pageTitle = 'Administrar pagos Yape'; require __DIR__ . '/../../includes/header.php'; require __DIR__ . '/../../includes/navbar.php';
?>
<main class="container"><section class="section"><h1 class="page-title">Pagos Yape</h1><p class="page-subtitle">Validación manual. Aprobar no ejecuta transferencias; reembolsar solo registra la decisión administrativa.</p>
<?php if ($message): ?><p class="alert alert-success"><?php echo htmlspecialchars($message, ENT_QUOTES, 'UTF-8'); ?></p><?php endif; ?><?php if ($error): ?><p class="alert alert-error"><?php echo htmlspecialchars($error, ENT_QUOTES, 'UTF-8'); ?></p><?php endif; ?>
<form class="filters" method="GET"><label>Estado <select name="estado"><option value="">Todos</option><?php foreach (Payment::states() as $state): ?><option value="<?php echo $state; ?>"<?php echo $filters['estado'] === $state ? ' selected' : ''; ?>><?php echo htmlspecialchars($state, ENT_QUOTES, 'UTF-8'); ?></option><?php endforeach; ?></select></label><label>ID evento <input name="evento_id" type="number" min="1" value="<?php echo $filters['evento_id'] ?: ''; ?>"></label><label>Fecha <input name="fecha" type="date" value="<?php echo htmlspecialchars($date, ENT_QUOTES, 'UTF-8'); ?>"></label><button class="btn btn-outline" type="submit">Filtrar</button></form>
<div class="table-wrapper"><table><thead><tr><th>Reserva</th><th>Cliente / evento</th><th>Cantidad</th><th>Monto</th><th>Operación</th><th>Fecha</th><th>Estado</th><th>Comprobante</th><th>Acciones</th></tr></thead><tbody>
<?php foreach ($payments as $payment): ?><tr><td><?php echo htmlspecialchars($payment['codigo_reserva'], ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars($payment['cliente'], ENT_QUOTES, 'UTF-8'); ?><br><?php echo htmlspecialchars($payment['evento'], ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo (int) $payment['cantidad']; ?></td><td>S/ <?php echo formatMoney($payment['monto']); ?></td><td><?php echo htmlspecialchars($payment['codigo_operacion'] ?? '', ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars($payment['fecha_pago'] ?? '', ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars($payment['estado'], ENT_QUOTES, 'UTF-8'); ?></td><td><?php if ($payment['comprobante']): ?><a class="btn btn-small btn-outline" target="_blank" href="<?php echo htmlspecialchars(base_url('views/client/payment_proof.php?id=' . (int) $payment['id']), ENT_QUOTES, 'UTF-8'); ?>">Ver</a><?php endif; ?></td><td>
<?php if ($payment['estado'] === 'en_revision'): ?><form class="inline-form" method="POST"><?php echo csrfField(); ?><input type="hidden" name="id" value="<?php echo (int) $payment['id']; ?>"><button class="btn btn-small btn-primary" name="action" value="approve" type="submit" data-confirm="¿Aprobar este pago?">Aprobar</button><input name="reason" placeholder="Motivo para rechazo"><button class="btn btn-small btn-danger" name="action" value="reject" type="submit" data-confirm="¿Rechazar este pago?">Rechazar</button></form><?php elseif ($payment['estado'] === 'aprobado'): ?><form class="inline-form" method="POST"><?php echo csrfField(); ?><input type="hidden" name="id" value="<?php echo (int) $payment['id']; ?>"><input name="reason" required placeholder="Motivo de reembolso"><button class="btn btn-small btn-danger" name="action" value="refund" type="submit" data-confirm="¿Registrar el reembolso?">Reembolsar</button></form><?php else: ?>Procesado<?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div></section></main><?php require __DIR__ . '/../../includes/footer.php'; ?>
