<?php
require_once __DIR__ . '/../../includes/auth.php'; require_once __DIR__ . '/../../controllers/ReservationController.php';
requireLogin(); requireRole('cliente'); $user = currentUser(); $id = (int) ($_GET['id'] ?? 0);
$reservation = ReservationController::getOwnedReservation($id, $user['id']); if (!$reservation) { redirect(base_url('views/errors/404.php')); }
$status = ReservationController::effectiveStatus($reservation); $pageTitle = 'Detalle de reserva'; require __DIR__ . '/../../includes/header.php'; require __DIR__ . '/../../includes/navbar.php';
?>
<main class="container"><section class="section"><h1 class="page-title">Reserva <?php echo htmlspecialchars($reservation['codigo_reserva'], ENT_QUOTES, 'UTF-8'); ?></h1>
<?php if (!empty($_GET['success'])): ?><p class="alert alert-success"><?php echo htmlspecialchars((string) $_GET['success'], ENT_QUOTES, 'UTF-8'); ?></p><?php endif; ?>
<?php if (!empty($_GET['error'])): ?><p class="alert alert-error"><?php echo htmlspecialchars((string) $_GET['error'], ENT_QUOTES, 'UTF-8'); ?></p><?php endif; ?>
<div class="glass-panel"><h2><?php echo htmlspecialchars($reservation['evento'], ENT_QUOTES, 'UTF-8'); ?></h2><ul class="meta-list"><li>Estado: <?php echo htmlspecialchars($status, ENT_QUOTES, 'UTF-8'); ?></li><li>Evento: <?php echo htmlspecialchars(date('d/m/Y H:i', strtotime($reservation['fecha_inicio'])), ENT_QUOTES, 'UTF-8'); ?></li><li>Lugar: <?php echo htmlspecialchars($reservation['lugar'], ENT_QUOTES, 'UTF-8'); ?></li><li>Cantidad: <?php echo (int) $reservation['cantidad']; ?></li><li>Precio: S/ <?php echo formatMoney($reservation['precio_unitario']); ?></li><li>Total: S/ <?php echo formatMoney($reservation['monto_total']); ?></li><li>Expiración: <?php echo htmlspecialchars($reservation['fecha_expiracion'] ? date('d/m/Y H:i:s', strtotime($reservation['fecha_expiracion'])) : 'No aplica', ENT_QUOTES, 'UTF-8'); ?></li><li>Pago: <?php echo htmlspecialchars($reservation['pago_estado'] ?? 'No registrado', ENT_QUOTES, 'UTF-8'); ?></li><?php if ($reservation['motivo_estado']): ?><li>Motivo: <?php echo htmlspecialchars($reservation['motivo_estado'], ENT_QUOTES, 'UTF-8'); ?></li><?php endif; ?></ul>
<?php if ($status === 'pendiente_pago'): ?><p data-countdown="<?php echo htmlspecialchars(date('c', strtotime($reservation['fecha_expiracion'])), ENT_QUOTES, 'UTF-8'); ?>">Calculando tiempo restante…</p><a class="btn btn-primary" href="<?php echo htmlspecialchars(base_url('views/client/reservation_payment.php?id=' . $id), ENT_QUOTES, 'UTF-8'); ?>">Registrar pago</a><form class="inline-form" method="POST" action="<?php echo htmlspecialchars(base_url('views/client/reservation_action.php'), ENT_QUOTES, 'UTF-8'); ?>"><?php echo csrfField(); ?><input type="hidden" name="id" value="<?php echo $id; ?>"><button class="btn btn-danger" type="submit" data-confirm="¿Cancelar esta reserva?">Cancelar reserva</button></form><?php elseif ($status === 'pago_en_revision'): ?><p class="alert alert-info">Tu pago está en revisión. No debes volver a pagarlo.</p><?php if ($reservation['pago_id']): ?><a class="btn btn-outline" href="<?php echo htmlspecialchars(base_url('views/client/payment_proof.php?id=' . (int) $reservation['pago_id']), ENT_QUOTES, 'UTF-8'); ?>" target="_blank">Ver comprobante</a><?php endif; ?><?php elseif ($status === 'confirmada'): ?><a class="btn btn-primary" href="<?php echo htmlspecialchars(base_url('views/client/reservation_confirmation.php?id=' . $id), ENT_QUOTES, 'UTF-8'); ?>">Ver confirmación imprimible</a><?php endif; ?>
<a class="btn btn-outline" href="<?php echo htmlspecialchars(base_url('views/client/event_detail.php?id=' . (int) $reservation['evento_id']), ENT_QUOTES, 'UTF-8'); ?>">Consultar evento</a></div></section></main><?php require __DIR__ . '/../../includes/footer.php'; ?>
