<?php
require_once __DIR__ . '/../../includes/auth.php'; require_once __DIR__ . '/../../controllers/ReservationController.php';
requireLogin(); requireRole('organizador'); $user = currentUser();
$stats = ReservationController::organizerStats($user['id']); $reservations = ReservationController::organizerReservations($user['id']);
$pageTitle = 'Reservas de mis eventos'; require __DIR__ . '/../../includes/header.php'; require __DIR__ . '/../../includes/navbar.php';
?>
<main class="container"><section class="section"><h1 class="page-title">Reservas de mis eventos</h1><p class="page-subtitle">Información de tus eventos únicamente. Los comprobantes y la aprobación pertenecen a administración.</p>
<div class="table-wrapper"><table><thead><tr><th>Evento</th><th>Aforo</th><th>Confirmadas</th><th>Retenidas</th><th>Disponibles</th><th>Ingresos aprobados</th></tr></thead><tbody><?php foreach ($stats as $item): $occupied = (int) $item['confirmadas'] + (int) $item['retenidas']; ?><tr><td><?php echo htmlspecialchars($item['titulo'], ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo (int) $item['cupo_total']; ?></td><td><?php echo (int) $item['confirmadas']; ?></td><td><?php echo (int) $item['retenidas']; ?></td><td><?php echo max(0, (int) $item['cupo_total'] - $occupied); ?></td><td>S/ <?php echo formatMoney($item['ingresos_aprobados']); ?></td></tr><?php endforeach; ?></tbody></table></div>
<h2>Reservas recientes</h2><div class="table-wrapper"><table><thead><tr><th>Código</th><th>Evento</th><th>Cliente</th><th>Cantidad</th><th>Estado</th><th>Fecha</th></tr></thead><tbody><?php foreach ($reservations as $reservation): ?><tr><td><?php echo htmlspecialchars($reservation['codigo_reserva'], ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars($reservation['evento'], ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars($reservation['cliente'], ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo (int) $reservation['cantidad']; ?></td><td><?php echo htmlspecialchars($reservation['estado'], ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars(date('d/m/Y H:i', strtotime($reservation['fecha_reserva'])), ENT_QUOTES, 'UTF-8'); ?></td></tr><?php endforeach; ?></tbody></table></div>
</section></main><?php require __DIR__ . '/../../includes/footer.php'; ?>
